name: 'Terraform Apply'

on:
  workflow_run:
    workflows: ['Terraform Plan']
    types:
      - completed

permissions:
  contents: read
  id-token: write
  pull-requests: write  # Needed to post a PR comment

jobs:
  terraform_apply:
    name: 'Terraform Apply'
    runs-on: ubuntu-latest
    environment: development

    defaults:
      run:
        shell: bash
        working-directory: ./mtc-terransible

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.OIDC_ROLE_ARN }}  
          aws-region: "eu-west-2"

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init

      # ✅ Add PR comment before running apply
      - name: Comment on PR
        uses: mshick/add-pr-comment@v2
        with:
          message: |
            🚀 **Terraform Apply Started!**
            This workflow was triggered after the **Terraform Plan** workflow completed.
            Check the logs [here](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }})
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          repo: ${{ github.repository }}
          issue: ${{ github.event.workflow_run.pull_requests[0].number }}
          allow-repeats: false

      - name: Terraform Apply
        run: terraform apply -input=false -auto-approve
