name: Terraform Security Scan

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  tfsec:
    name: Run TFSec Security Scan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: latest

      - name: Run TFSec Security Scan
        uses: aquasecurity/tfsec-action@v1.0.3
        with:
          soft_fail: false #Set to true if you don’t want failures to block merges